### ISSUE TITLE
Magenta Studio not running Ableton Live 10.1

### ISSUE THREAD

**Issue by gpvillamil** [tensorflow/magenta-studio#27]
I am sporadically not able to run the Magenta Studio plugins in Ableton Live 10.1

I open the .amxd file and have studio plugins in a column, but they are greyed out and do not respond.

However, I have been able to get it to run before. I saved that Live Set, and when I re-opened, the plugins were greyed out and the buttons did not respond.
<img width="731" alt="Screen Shot 2019-06-11 at 3 15 09 PM" src="https://user-images.githubusercontent.com/342238/59310667-f7464180-8c5b-11e9-8d1b-f55ba36845c1.png">

**Comment by adarob** [comment]
You should be able to get it to work by updating to the latest version on the website. Please let us know if it doesn't work!

**Comment by gpvillamil** [comment]
It is working well now!

**Comment by radamski-ai** [comment]
I have similar issue with plugin for macOS. Plugin is greyed in Ableton, does not respond for clicks to launch items.
